In [3]:
import pandas as pd
import numpy as np
import string

In [4]:
df = pd.read_csv("dataset/movie_dataset.csv")
df.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,15-07-2010,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,05-11-2014,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,16-07-2008,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,15-12-2009,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,25-04-2012,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [5]:
df_selected = df.dropna()

In [6]:
df_selected[['title','original_title']].sample(15)

,title,original_title
17725,Worry Dolls,Worry Dolls
34032,New Life,New Life
12788,Atlas Shrugged: Part I,Atlas Shrugged: Part I
20127,Lupin the 3rd,ルパン三世
405334,Puffing Iron,Puffing Iron
456690,Liberation: Between Two Fires,Kurtuluş: İki Ateş Arasında
6815,Lake Mungo,Lake Mungo
37034,Ramayana: The Legend of Prince Rama,ラーマーヤナ ラーマ王子伝説
173326,Love Live! Fest,ラブライブ！フェス
563563,"Lust, Lies, and Polygamy","Lust, Lies, and Polygamy"
49515,Flatland: The Film,Flatland: The Film
359916,The Finger Food Cafe Show: A Christmas Gift,The Finger Food Cafe Show: A Christmas Gift
15440,Caravaggio,Caravaggio
1625,Hustlers,Hustlers
8779,Fierce Creatures,Fierce Creatures

In [7]:
df_selected.drop(
    columns=['id','vote_average','vote_count','status','release_date','revenue','runtime',
             'budget','backdrop_path','homepage','imdb_id','original_language','original_title'
             ,'poster_path','production_companies','production_countries','spoken_languages'],
    inplace=True)

C:\Users\patel\AppData\Local\Temp\ipykernel_25452\4160138336.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected.drop(

In [8]:
df_selected

,title,adult,overview,popularity,tagline,genres,keywords
0,Inception,False,"Cobb, a skilled thief who commits corporate es...",83.952,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc..."
1,Interstellar,False,The adventures of a group of explorers who mak...,140.241,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,..."
2,The Dark Knight,False,Batman raises the stakes in his war on crime. ...,130.643,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f..."
3,Avatar,False,"In the 22nd century, a paraplegic Marine is di...",79.932,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ..."
4,The Avengers,False,When an unexpected enemy emerges and threatens...,98.082,Some assembly required.,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...
1039991,Killers of the Flower Moon,False,When oil is discovered in 1920s Oklahoma under...,90.719,Greed is an animal that hungers for blood.,"Crime, Drama, Thriller","husband wife relationship, based on novel or b..."
1041646,Faceless,False,Faceless is a documentary film about the worki...,0.659,Inside An Inpatient Psychiatry Unit,Documentary,"toronto, canada, medicine, psychiatric hospita..."
1046484,Blade Warrior,False,Jack is a martial arts-trained cop who is work...,0.600,They picked the wrong cop to mess with!,Action,"martial arts, cop, revenge, kingpin, mob"
1047171,I Want Abs,False,"After looking at countless ""before and after"" ...",0.600,A Documentary For Regular People Who Want To G...,Documentary,"diet, vegetable juice, raw food, smoothies, ju..."
1048414,Cold Journey,False,"In this feature drama, a Canadian Indigenous y...",0.600,"He was called an apple, Red on the outside Whi...",Drama,"indigenous, native american"

In [9]:
df_selected['keywords'] = df_selected['keywords'].apply(lambda x: x.translate(str.maketrans('','',string.punctuation)))
df_selected['genres'] = df_selected['genres'].apply(lambda x: x.translate(str.maketrans('','',string.punctuation)))
df_selected['overview'] = df_selected['overview'].apply(lambda x: x.translate(str.maketrans('','',string.punctuation)))
df_selected['tagline'] = df_selected['tagline'].apply(lambda x: x.translate(str.maketrans('','',string.punctuation)))

df_selected['overview']

C:\Users\patel\AppData\Local\Temp\ipykernel_25452\1428443096.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['keywords'] = df_selected['keywords'].apply(lambda x: x.translate(str.maketrans('','',string.punctuation)))
C:\Users\patel\AppData\Local\Temp\ipykernel_25452\1428443096.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['genres'] = df_selected['genres'].apply(lambda x: x.translate(str.maketrans('','',string.punctuation)))
C:\Users\patel\AppData\Local\Temp\ipykernel_25452\1428443096.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['overview'] = df_selected['overview'].apply(lambda x: x.translate(str.maketrans('','',string.punctuation)))
C:\Users\patel\AppData\Local\Temp\ipykernel_25452\1428443096.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['tagline'] = df_selected['tagline'].apply(lambda x: x.translate(str.maketrans('','',string.punctuation)))

0          Cobb a skilled thief who commits corporate esp...
1          The adventures of a group of explorers who mak...
2          Batman raises the stakes in his war on crime W...
3          In the 22nd century a paraplegic Marine is dis...
4          When an unexpected enemy emerges and threatens...
                                 ...
1039991    When oil is discovered in 1920s Oklahoma under...
1041646    Faceless is a documentary film about the worki...
1046484    Jack is a martial artstrained cop who is worki...
1047171    After looking at countless before and after ph...
1048414    In this feature drama a Canadian Indigenous yo...
Name: overview, Length: 9457, dtype: object

In [10]:
df_selected['content'] = df_selected['overview']+ ' ' + df_selected['tagline'] + ' ' + df_selected['keywords'] + ' ' + df_selected['genres']

C:\Users\patel\AppData\Local\Temp\ipykernel_25452\2318561818.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['content'] = df_selected['overview']+ ' ' + df_selected['tagline'] + ' ' + df_selected['keywords'] + ' ' + df_selected['genres']

In [11]:
df_selected

,title,adult,overview,popularity,tagline,genres,keywords,content
0,Inception,False,Cobb a skilled thief who commits corporate esp...,83.952,Your mind is the scene of the crime,Action Science Fiction Adventure,rescue mission dream airplane paris france vir...,Cobb a skilled thief who commits corporate esp...
1,Interstellar,False,The adventures of a group of explorers who mak...,140.241,Mankind was born on Earth It was never meant t...,Adventure Drama Science Fiction,rescue future spacecraft race against time art...,The adventures of a group of explorers who mak...
2,The Dark Knight,False,Batman raises the stakes in his war on crime W...,130.643,Welcome to a world without rules,Drama Action Crime Thriller,joker sadism chaos secret identity crime fight...,Batman raises the stakes in his war on crime W...
3,Avatar,False,In the 22nd century a paraplegic Marine is dis...,79.932,Enter the world of Pandora,Action Adventure Fantasy Science Fiction,future society culture clash space travel spac...,In the 22nd century a paraplegic Marine is dis...
4,The Avengers,False,When an unexpected enemy emerges and threatens...,98.082,Some assembly required,Science Fiction Action Adventure,new york city superhero shield based on comic ...,When an unexpected enemy emerges and threatens...
...,...,...,...,...,...,...,...,...
1039991,Killers of the Flower Moon,False,When oil is discovered in 1920s Oklahoma under...,90.719,Greed is an animal that hungers for blood,Crime Drama Thriller,husband wife relationship based on novel or bo...,When oil is discovered in 1920s Oklahoma under...
1041646,Faceless,False,Faceless is a documentary film about the worki...,0.659,Inside An Inpatient Psychiatry Unit,Documentary,toronto canada medicine psychiatric hospital m...,Faceless is a documentary film about the worki...
1046484,Blade Warrior,False,Jack is a martial artstrained cop who is worki...,0.600,They picked the wrong cop to mess with,Action,martial arts cop revenge kingpin mob,Jack is a martial artstrained cop who is worki...
1047171,I Want Abs,False,After looking at countless before and after ph...,0.600,A Documentary For Regular People Who Want To G...,Documentary,diet vegetable juice raw food smoothies juicing,After looking at countless before and after ph...
1048414,Cold Journey,False,In this feature drama a Canadian Indigenous yo...,0.600,He was called an apple Red on the outside Whit...,Drama,indigenous native american,In this feature drama a Canadian Indigenous yo...

In [12]:
df_selected['content'] = df_selected['content'].str.lower()
df_selected['content']

C:\Users\patel\AppData\Local\Temp\ipykernel_25452\3546926580.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['content'] = df_selected['content'].str.lower()

0          cobb a skilled thief who commits corporate esp...
1          the adventures of a group of explorers who mak...
2          batman raises the stakes in his war on crime w...
3          in the 22nd century a paraplegic marine is dis...
4          when an unexpected enemy emerges and threatens...
                                 ...
1039991    when oil is discovered in 1920s oklahoma under...
1041646    faceless is a documentary film about the worki...
1046484    jack is a martial artstrained cop who is worki...
1047171    after looking at countless before and after ph...
1048414    in this feature drama a canadian indigenous yo...
Name: content, Length: 9457, dtype: object

In [13]:
df_final = df_selected.drop(columns=['genres','overview','keywords','tagline'])
df_final['title'] = df_final['title'].str.lower()
df_final

,title,adult,popularity,content
0,inception,False,83.952,cobb a skilled thief who commits corporate esp...
1,interstellar,False,140.241,the adventures of a group of explorers who mak...
2,the dark knight,False,130.643,batman raises the stakes in his war on crime w...
3,avatar,False,79.932,in the 22nd century a paraplegic marine is dis...
4,the avengers,False,98.082,when an unexpected enemy emerges and threatens...
...,...,...,...,...
1039991,killers of the flower moon,False,90.719,when oil is discovered in 1920s oklahoma under...
1041646,faceless,False,0.659,faceless is a documentary film about the worki...
1046484,blade warrior,False,0.600,jack is a martial artstrained cop who is worki...
1047171,i want abs,False,0.600,after looking at countless before and after ph...
1048414,cold journey,False,0.600,in this feature drama a canadian indigenous yo...

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

# what is TFidfVectorizer?
# It gives higher importance to important words and lower importance to common words.

tfidf = TfidfVectorizer(stop_words='english')
matrix = tfidf.fit_transform(df_final['content'])

matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 360416 stored elements and shape (9457, 36844)>

In [15]:
df_final.shape

(9457, 4)

In [16]:
matrix.shape

(9457, 36844)

In [17]:
adult = df_final['adult'].values.reshape(-1,1)
popularity = df_final['popularity'].values.reshape(-1,1)

In [18]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
popularity = minmax.fit_transform(popularity)

In [19]:
from scipy.sparse import hstack

final_matrix = hstack([adult,popularity,matrix])
final_matrix

<COOrdinate sparse matrix of dtype 'float64'
	with 369858 stored elements and shape (9457, 36846)>

In [20]:
from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors()
fit_model = model.fit(final_matrix)

In [21]:
def recommend(name):

    name = name.lower()
    if name not in df_final['title'].values:
        print("Movie not found")
        return
    
    point = df_final.loc[df_final['title'] == name,['adult','popularity','content']]


    matrix_trf = tfidf.transform(point['content'])
    point_adult = point['adult'].values.reshape(-1,1)
    point_pop = point['popularity'].values.reshape(-1,1)

    point_pop = minmax.transform(point_pop)

    final_point = hstack([point_adult,point_pop,matrix_trf])

    _, indices = model.kneighbors(final_point, n_neighbors=5)

    for i in indices[0]:
        print(df_final.iloc[i]['title'])

In [28]:
recommend('iron man')

iron man
iron man 3
iron man 2
inhumans: the first chapter
captain marvel